# Generated by Django 3.1.5 on 2021-02-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default-post.jpg', upload_to='post_images'),
        ),
    ]
